spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/miniproj
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    
plan-api:
  messages: 
   planSaveSucc: Plan Saved Successfully...
   planSaveFail: Plan Not Saved.
   planUpdateSucc: Plan updated Successfully...
   planUpdateFail: Plan not updated.
   planDeleteSucc: Plan deleted successfully...
   planDeleteFail: Plan Not deleted.
   planStatusChanageSucc: Status is changed...
   planStatusChangeFail: Status not changed. 